### PR TITLE
Update TGInaccessibleMessage.swift

### PR DESCRIPTION
**Pull request by crescentheaded**
> Always 0.

### CODE REVIEW

**Comment by nerzh** [comment]
Hello, ok, but you do not understand one nuance, this code is generated. And at the next release, the generator will delete all your changes.

**Comment by nerzh** [comment]
Снимок экрана 2024-01-21 в 02 22 25

I understand that you can write it more beautifully, but then you will have to manually check all the classes and changes with your eyes every day. Search manually every day for these changes on the documentation site in the Telegram API. If you're ready for it, you can try it. Now all classes fully comply with the official Telegram API.

**Comment by nerzh** [comment]
if in this class the field is always 0, then this is a question not for this library, but for the developers of the telegram api, I will not make my class changes to the official telegram api, simply because it is convenient at the moment.

**Comment by crescentheaded** [comment]
didn't know about automatic generation. roger that

**Pull request closed without merging**
